# Generated by Django 4.2.3 on 2023-10-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authors', models.CharField(choices=[], max_length=250, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(max_length=25000, verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False, verbose_name='Статус')),
                ('authors', models.CharField(choices=[], max_length=250, verbose_name='Автор')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заметки',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created'],
            },
        ),
    ]
