# Generated by Django 4.1.6 on 2023-10-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(max_length=25000, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='authors',
            field=models.CharField(choices=[('innaro', 'innaro'), ('roki1166', 'roki1166')], max_length=250, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='note',
            name='authors',
            field=models.CharField(choices=[('innaro', 'innaro'), ('roki1166', 'roki1166')], max_length=250, verbose_name='Автор'),
        ),
    ]
